title: Open Ideas
timezone: UTC
baseurl: /open-ideas
url: https://dorian.mors.es
collections:
  ideas:
    permalink: /:collection/:name
    output: true
defaults:
  - scope:
      path: ""
      type: ideas
    values:
      layout: idea
gems:
  - jekyll-octicons
style:
  sass:
    style: compressed
images_path: /assets/img
sass:
  sass_dir: _sass
repo: "https://www.github.com/dsmrs/open-ideas"
