title: Open Ideas
timezone: UTC
collections:
  ideas:
    permalink: /:collection/:name
    output: true
plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/page:num/"
defaults:
  - scope:
      path: ""
      type: ideas
    values:
      layout: idea
gems:
  - jekyll-octicons
